### PR TITLE
Support download sonar-scanner from a mirror

### PR DESCRIPTION
**Pull request by gucong3000**
close #2

### CODE REVIEW

**Comment by gucong3000** [comment]
Because of the Internet control in my country, I tried three times, the download failed, it took about 1 hours, finally succeeded in the fourth time. So it's hard to work without domestic mirror support.

**Comment by gucong3000** [comment]
I am in China.

**Comment by gucong3000** [comment]
Here are some topics that we can't normally discuss.
https://en. wikipedia. Org/wiki/great_firewall

Most Chinese JS developers use this mirror to install a binary file that the NPM package relies on.
https://npm.taobao.org/mirrors

**Comment by bellingard** [comment]
Thanks!

**Comment by crossjs** [comment]
Tthis PR should be reversed.
There is no sonar mirrors in cnpm: https://github.com/cnpm/mirrors/issues/158

**Pull request merged**
