### PR TITLE
Update parameter of API & CLI

### PR DESCRIPTION
**Pull request by gucong3000**
Changed:
- Add dedicated "organization" parameter on `README.md`
- support all arguments from original SonarQube Scanner
- remove prefix of `sonar.links.scm`
- auto add prefix to parameter name for CLI & API

### CODE REVIEW

**Comment by gucong3000** [comment]
CLI usage:
```shell
sonar-scanner -serverUrl=127.0.0.1:9000 -organization=default
```

Node API usage:
```javascript
    sonarqubeScanner({
        options: {
            serverUrl: "127.0.0.1:9000",
            organization: "default",
        }
    }, callback);
```

**Comment by gucong3000** [comment]
image
@bellingard TRAVIS-CI configuration may not be correct, did you turn off the construction of PR in the graphical interface

**Comment by gucong3000** [comment]
Automation review is not work for this base.

**Comment by gucong3000** [comment]
image

**Comment by gucong3000** [comment]
I should rebase this PR after #30

**Comment by bellingard** [comment]
I'm sorry @gucong3000 , you are mixing too many features/improvements in this PR - which makes it hard to review.
Please create a PR for each dedicated feature that you want to push, this will help me review it faster.
Thanks!

**Comment by gucong3000** [comment]
> you are mixing too many features

You are right. Please review #30 first.

**Comment by bellingard** [comment]
Too old PR - closing it.

**Pull request closed without merging**
