### PR TITLE
Bump SONAR_SCANNER_VERSION to 4.7.0.2747

### PR DESCRIPTION
**Pull request by rantoniuk**

### CODE REVIEW

**Comment by rantoniuk** [comment]
@bellingard are you ok for bumping this to current version?

**Comment by dzienisz** [comment]
why it have 25 Code Smells?

**Review by dzienisz — APPROVED** [review]

**Comment by dzienisz** [comment]
@gabssnake It should be the highest priority for next release in my opinion.

I checked and this is the newest version: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

@rantoniuk can you push this commit again to run another sonarcloud scan?

@gabssnake can you add us to this project on sonarcloud?

**Comment by gabssnake** [comment]
Hey guys, if you can make the CI checks pass I'll be happy to merge this change :+1:

**Comment by dzienisz** [comment]
@gabssnake I can just replicate that in new PR ¯\_(ツ)_/¯

**Comment by dzienisz** [comment]
https://github.com/bellingard/sonar-scanner-npm/pull/151

**Comment by gabssnake** [comment]
Closing this in favor of #151

**Pull request closed without merging**
