### PR TITLE
add SONARQUBE_SCANNER_HOME to override homedir

### LINKED ISSUE #56: ENV for something like SONARQUBE_SCANNER_HOME
https://github.com/bellingard/sonar-scanner-npm/blob/e65aa4cb2b693511fb0829ff2d64bf1306bd032c/dist/sonarqube-scanner-executable.js#L61

Currently the install location is set to `$HOME`, would be great to set manually in order to play well in container based CI system, for caching mostly.

```javascript
process.env.SONARQUBE_SCANNER_HOME || os.homedir()
```

### PR DESCRIPTION
**Pull request by qqshfox**
Fixes #56

### CODE REVIEW

**Comment by AACarloAlmeida** [comment]
@bellingard This would be helpful

**Comment by sidharta** [comment]
I'm not sure if it's the same issue I had, but I could change it by simply changing the `HOME` variable during execution. For instance:
```
HOME=. sonar-scanner 
```

**Comment by gabssnake** [comment]
Hey @qqshfox, are you still interested in this?

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen if you update the PR.

**Pull request closed without merging**
