### PR TITLE
Update node dependencies

### PR DESCRIPTION
**Pull request by Gnuk**
Update node dependencies

Goal:

* [x] Have less obsoletes as possible
* [x] Replace gulp with npm scripts
* [ ] Remove vulnerabilities

### CODE REVIEW

**Comment by Gnuk** [comment]
@bellingard Do you know why all Travis pipelines are failing ?

**Comment by bellingard** [comment]
@Gnuk Yes, there is a bug on Travis side with the SonarCloud add-on for external PRs :-(

Maybe what you can do for now, to not be bothered by this, is to find a way in the Travis YML file to run "npm run test" in the case of external PRs, and "npm run ci" in all other cases.

**Comment by bellingard** [comment]
@Gnuk I reviewed your PR, and I think it should be merged right now. I don't know what you meant to do about the vulnerabilities check, but looks like this at least fixing #84 so I think we can proceed.
Thanks for your contribution!

**Comment by Gnuk** [comment]
@bellingard Yes, it's not sonar vulnerabilities but vulnerabilities due to some dependencies (found with npm audit). Thank you for the review and you're welcome!

**Pull request merged**
