### PR TITLE
extract report info from package.json

### PR DESCRIPTION
**Pull request by gucong3000**
- `sonar.testExecutionReportPaths` when install `mocha-sonarqube-reporter`
- `sonar.javascript.lcov.reportPath`: `lcov.info` will auto pickup if it exists.

### CODE REVIEW

**Comment by bellingard** [comment]
These improvements are very interesting, thanks @gucong3000 .

Still, to accept the PR, I'd love to see those use cases covered by unit tests in https://github.com/bellingard/sonar-scanner-npm/blob/master/specs/sonarqube-scanner-params-test.js - to prevent any regression in the future.

Thanks!

**Comment by gucong3000** [comment]
some thing wrong with codacy, I can not open this url:
image

**Comment by bellingard** [comment]
@gucong3000 I removed Codacy analysis - I had activated it only for test purposes.

**Comment by gucong3000** [comment]
@bellingard
I would like to help add Travis-CI & ESLint

**Comment by gucong3000** [comment]
Recommend some services:
- Travis CI/CircleCI/AppVeyor
- Codecov

**Comment by bellingard** [comment]
The repo is already built on TravisCI and analyzed on SonarCloud (see the badge on the README file => https://sonarcloud.io/dashboard?id=sonarqube-scanner)

SonarCloud does not support external PR analysis yet, but it's coming soon. So I'll wait for this.

**Comment by bellingard** [comment]
Tested the PR locally, everything looks good to me. Merging right now.

Thanks!

**Pull request merged**
