### PR TITLE
Modify README for customScanner sample usage.

### PR DESCRIPTION
**Pull request by romanbalayan**
- Explicitly include requirement to add sonar-scanner location to PATH env variable
- Complete the example code usage for customScanner
- Will fix issue #141

### CODE REVIEW

**Review by dzienisz — APPROVED** [review]

**Comment by romanbalayan** [comment]
Hi @dzienisz ,

Contributing as part of hacktoberfest 2022 (https://hacktoberfest.com/). If it's not too much of a bother, will it be okay to tag the PR with `hacktoberfest-accepted` label, just to it can be officially tagged as participating?

Thank you so much.

**Comment by dzienisz** [comment]
Yes, thanks!

**Comment by gabssnake** [comment]
Hi @romanbalayan, I'd rather keep the example code shorter, only mentioning `require('sonarqube-scanner').customScanner;` since it is the only meaningful part.

Have you tried what you are suggesting, or are you basing this on inference?

**Comment by romanbalayan** [comment]
Hi @gabssnake,

Sure, will take out the code block, and just maintain the specific change required when using the customScanner.

And yes, tried this out prior to creating the pull request.

**Comment by romanbalayan** [comment]
Hi @gabssnake,

Anything I should be looking out for this?

Also @dzienisz, sorry to bother again, is it okay for the PR to be tagged with the `hacktoberfest-accepted` label?

Thanks!

**Pull request merged**
