### PR TITLE
Update Scanner CLI to 4.2.0.1873

### PR DESCRIPTION
**Pull request by jacek-poreda-sonarsource**

### CODE REVIEW

**Comment by guillaumelamirand** [comment]
@jacek-poreda-sonarsource I am interested by the version upgrade; did you check why the CI failed?

**Comment by jacek-poreda-sonarsource** [comment]
Yes, it seems like Travis job is trying to execute SQ analysis and connect to SQ instance on localhost which is obviously unavailable

**Comment by guillaumelamirand** [comment]
It seems the project is dead as many issues and PR don't have any response from author, also last commit was almost 1 year ago...

**Comment by bellingard** [comment]
Nope, the project is not dead, just missing time to work on it...

**Comment by guillaumelamirand** [comment]
That's good to ear because your project is really helping.
Thank you for taking the time for this PR.

**Pull request merged**
