### PR TITLE
docs: fix alpine case broken link

### LINKED ISSUE #123: Problem to access the link of Docker manual installation on Readme.MD
Hello guys,

I am trying to run this package on docker, but I am having trouble with his message: .../jre/bin/java: not found. 

So while I was reading the docs I saw this step:
Screen Shot 2021-05-03 at 5 28 48 PM

But the link is not working, someone can help me?

Thx

### PR DESCRIPTION
**Pull request by sebaplaza**
The href for the alpine glibc problem solution is broken.

This PR replaces the href.

Closes #123

### CODE REVIEW

**Comment by gabssnake** [comment]
Hi @sebaplaza the new link seems to be broken too.
If you can fix it I'll be happy to merge this change :)

**Comment by sebaplaza** [comment]
Hello @gabssnake ,

the new link is working for me, do you still have the issue ? maybe a temporary network problem ?

**Review by dzienisz — APPROVED** [review]

**Comment by dzienisz** [comment]
@sebaplaza the webpage under old domain is not longer available

**Comment by sebaplaza** [comment]
This one (the new one) is working for you ?

https://laptrinhx.com/docker-for-mac-alpine-glibc-issues-802275018

**Comment by gabssnake** [comment]
Thanks @sebaplaza

**Pull request merged**
